### PR TITLE
Meropis clouds

### PR DESCRIPTION
**Pull request by keneanung**
- Depends on #21
- if the map is set up correctly, this allows us to use the meropis clouds for shortcuts

### CODE REVIEW

**Comment by jgh713** [comment]
I'm unsure of whether or not the game's map has this sort of information in it.

The crowdmap, however, is certainly not set up for this, unless something has changed recently. Last I checked, the Duanathar areas are marked as "Prime", and every single other area is marked as "Off" continent (which the mapper sometimes refers to as Meropis), with no distingushing between outer areas.

**Comment by keneanung** [comment]
Correct. But I've been in close contact with @QwindorRousseau to adapt the map accordingly. The plan is to further distinguish continents, which would enable us to use more fast travel commands like `gare` or the Island Wings.

**Comment by QwindorRousseau** [comment]
There is a map pull request waiting for the coding to be done for the new wings and such that has all the continent information adjusted to make them work properly. When the scripting is done and this pull request put in and put up for update @keneanung will merge the pull request for the new map as well so they can be updated at the same time.

**Comment by QwindorRousseau** [comment]
The continents for island wings are main, island, meropis, and north continents. Command to use them is duanatharic. The room number is 47571.

**Pull request merged**
