### PR TITLE
missed a couple global variables

### PR DESCRIPTION
**Pull request by tsartin**
Removing a a variable and function out of the global namespace and into mmp that I missed.

### CODE REVIEW

**Comment by mccarp** [comment]
I'm not sure if it's good for doSpeedWalk to be moved into the mmp namespace, as it's my understanding that that particular function is called when you click on a room in mudlet's map. Can you double check if this breaks that functionality?

**Comment by vadi2** [comment]
It would indeed, see https://wiki.mudlet.org/w/Mapping_script#Making_your_own_mapping_script

**Comment by tsartin** [comment]
Good catch, I'll undo that

**Review by vadi2 — APPROVED** [review]

**Comment by vadi2** [comment]
Thank you!

**Pull request merged**
