### PR TITLE
Reduced redundancy within the code.

### PR DESCRIPTION
**Pull request by mccarp**
Sorry in advance, I know this is a big PR.

Here's what's in it!

Manually reformatted the configs to be more user-readable, and replaced all config functions that only contained an echo, or an echo and a clear pathe cache with calls to mmp.changeBoolFunc, which provides a suitable echo. Changing a config inherently cleared the path cache, so having it called again was redundant.

I also removed other places where the path cache was cleared unnecessarily throughout the code, which was an undesirable behavior. It should only be cleared if changes are done to settings or the map itself - because temporary exits would be established in the same locations on subsequent runs, there is no need to clear the path cache after creating temporary wings exits.

Within the wings code itself, I cut down on unnecessary function calls by relying on existing variables, and creating a temporary area variable instead of calling getRoomArea during every single check.

I also removed the game specific gone-outdoors-try-to-use-wings scripts, in favor of a generic one which works for any game that uses wings or similar items.

### CODE REVIEW

**Comment by vadi2** [comment]
Hey, thanks for the improvements you've done!

> there is no need to clear the path cache after creating temporary wings exits.

Wouldn't this be an issue if the path cache had a version without the newly-created exits?

**Review by vadi2 — COMMENTED** [review]
Looks good, could we get a lot of testing on this to make sure existing functionality all still works? @ThaisenLV @PapaGuacamole @Hevlikn @JustCylon

**Comment by mccarp** [comment]
> Hey, thanks for the improvements you've done!
> 
> > there is no need to clear the path cache after creating temporary wings exits.
> 
> Wouldn't this be an issue if the path cache had a version without the newly-created exits?

In general use I don't think this would happen, but I did look look deeper and it looks like there are some mmp.getPath calls that aren't accompanied by linking/clearing the externals. I think I will add the path cache clears back into the wings scripts, but I think the way the path cache clears work in general should get a deeper look. If it's being cleared super consistently, is it even necessary to cache at all?

**Comment by vadi2** [comment]
Yeah, that way paths used repeatedly between the calls have a performance benefit. Helps with auto walking for sure on the same areas and it's never been a downside.

**Comment by mccarp** [comment]
I tossed the path clears back into all the wings scripts, but I really think the way it all works does need a much closer look at some point. As it is, the cache has (and will continue to be) cleared before every actual goto path on any of the games with wings code, meaning that it won't have any positive impact - however, because not every place mmp.getpath is called is wrapped by raised events to link/unlink wings, the cache can get populated by routes that ignore wings and therefor would need to be cleared. I've though briefly of embedding the events within mmp.getpath itself for much more consistent behavior., but I am worried of the performance impact that would have in instances where code generates a ton of paths (ie, finding the closest border of an area), because it could be executing the wings stuff half a dozen times or more, instead of just once.

**Comment by ThaisenLV** [comment]
Hey all, been MIA the last few days but I'll give this version a shot tonight after work!

**Comment by ThaisenLV** [comment]
So far so good with autowalking, using wings, orb settings...is there anything else specifically I should be testing?

**Comment by ThaisenLV** [comment]
Anyone else able to test this? It is really good stuff I think the majority of the playerbase would appreciate! :)

**Comment by vadi2** [comment]
Without testers, we can't move forward. If you like using the mapper, give back by testing this :)

**Review by vadi2 — APPROVED** [review]

**Pull request merged**
