### PR TITLE
Attempt to "Clean up globals exposure"

### PR DESCRIPTION
**Pull request by tsartin**
Attempting to clean up globals exposure mentioned in #166

### CODE REVIEW

**Comment by vadi2** [comment]
Very nice improvement!

Where is the note that you mention?

**Comment by tsartin** [comment]
On the current version, it is line 5691 "-- populated by Mudlet from getPath() and gotoRoom()"

**Comment by vadi2** [comment]
Ah that only applies to speedWalkPath and speedWalkDir, see https://wiki.mudlet.org/w/Manual:Lua_Functions#getPath. Mind improving the comment so the next person isn't confused also?

**Comment by tsartin** [comment]
Done!

**Review by vadi2 — APPROVED** [review]
Looks great to me on a read through!

**Pull request merged**
