### PR TITLE
Fix for issue 47, goto not stopping once it gets to the area you wanted.

### PR DESCRIPTION
**Pull request by PapaGuacamole**
New variable container _mmp.speedWalk_ created, includes variable _type_, which is either 'area' or 'room'. Affects how repathing is done when using wings, etc.

### CODE REVIEW

**Comment by vadi2** [comment]
Does this also catch if you are suddenly transported to the area somehow?

**Comment by PapaGuacamole** [comment]
No, this doesn't do any kind of checks on current area vs destination area, it just changes how it repaths on using wings, etc

**Comment by keneanung** [comment]
I lost track... is this ready to go?

**Comment by PapaGuacamole** [comment]
I believe so

**Comment by PapaGuacamole** [comment]
When I tried to use the formatter, it deleted loads of code. I have made a couple of minor tweaks to the harness code to, to remove a function no longer required (the changes are included in the crowdmap)

**Comment by PapaGuacamole** [comment]
renamed local goto to whereAmIGoing, formatter worked OK

**Comment by PapaGuacamole** [comment]
I'm confused now by this conflict. The code I've uploaded matches the <<<<< Master section:
  for k, v in pairs(temp) do
    maptable[k:lower()] = v
  end
  local destinationRoom = maptable[where]
  if destinationRoom then
    mmp.gotoRoom(destinationRoom, dashtype)
    return

Not sure what I can do to resolve this as I'm not showing any differences in my local file to the uploaded one, and it's the output from the formatter.

**Pull request merged**
