### PR TITLE
Update mapper download URLs

### LINKED ISSUE #10: Update launchpad URLs
All of the launchpad URLs in https://github.com/IRE-Mudlet-Mapping/ire-mapping-script/blob/master/mudlet-mapper.xml need to be updated to something more proper.

### PR DESCRIPTION
**Pull request by keneanung**
This fixes #10 when merged.

I also updated the contributing file as the version file and the version info in the xml are changed by travis now.

### CODE REVIEW

**Comment by keneanung** [comment]
@vadi2 any comments?

**Comment by vadi2** [comment]
+1

**Comment by keneanung** [comment]
@vadi2 The mapper should be ready for a bazaar update now. Use the files from http://ire-mudlet-mapping.github.io/ire-mapping-script/downloads/mudlet-mapper.xml and http://ire-mudlet-mapping.github.io/ire-mapping-script/downloads/version to check into bazaar

**Comment by vadi2** [comment]
[Done](https://bazaar.launchpad.net/~mudlet-makers/mudlet/mapper-lua/revision/218). Seems to have worked, the update worked for me ingame.

**Comment by keneanung** [comment]
Perfect. Thank you very much!

**Pull request merged**
