### PR TITLE
Added code for setting an outdoors flag.

### PR DESCRIPTION
**Pull request by mccarp**
This is to help prepare the crowdmap for better wings pathfinding, because as it is it's impossible to tell a room which hasn't been visited/crowdmapped from one which is outdoors, as both are missing an 'indoors' flag in the userdata.

### CODE REVIEW

**Review by vadi2 — COMMENTED** [review]
How does it look like in practice?

Wondering how does it look like when a room is flipped from outdoors to indoors or vice versa.

**Comment by mccarp** [comment]
This will have two userData tags, with indoors holding a value of either "y" or "" and outdoors holding a value of either "" or "y", with them being opposites of each other. While this may be a little clunky, I wanted to leave the functionality of the indoors userdata thing completely unchanged because other people may have scripts which rely on it.

**Comment by vadi2** [comment]
Sure, I just mean the messages that the user sees - we can align those to make sense

**Comment by vadi2** [comment]
Wrong button

**Comment by mccarp** [comment]
Okay, I rearranged it a little. The echoes to the end user will be the same as they were originally, just 'Updated room to be outdoors' or 'updated room to be indoors'.
image

**Comment by ThaisenLV** [comment]
@vadi2 and @mccarp is this what we want, was walking around a little testing this out.... the indoors tag is staying, but it is just "" instead of "y". Just want to make sure this will work out like it is supposed to.

image

**Comment by ThaisenLV** [comment]
Tried vice versa and an indoor room will show no outdoor tag at all.
image

**Comment by vadi2** [comment]
It would make sense to have just one tag per room with a `y` I believe, what do you think @mccarp?

**Comment by mccarp** [comment]
Sure! They're functionally identical (getRoomUserData on a nonexistent key also returns ""), but I agree it looks a little cleaner. Did a quick change to clear a key instead of setting it to "".

**Review by vadi2 — APPROVED** [review]

**Pull request merged**
